### PR TITLE
Adapt to latest electron package

### PR DESCRIPTION
**Pull request by yshrsmz**
In the latest electron release, executable name has been renamed to `Electron.app` from `Atom.app`

### CODE REVIEW

**Comment by joaomoreno** [comment]
This actually works, but what about people that are stuck on an old version of Atom Shell? I don't want to break them, we should not simply assume the app is Electron.app. The code should be able to accommodate both situations.

**Comment by yshrsmz** [comment]
You are right, let me rethink about it...
Or, do you have any plan to implement this feature?
I am wondering if I'd better wait :)

**Comment by joaomoreno** [comment]
I won't be able to get on it surely within at least a couple of weeks.

**Comment by joaomoreno** [comment]
Closing as per #17

**Pull request closed without merging**
